name: Tests

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  hello-world:
    runs-on: ubuntu-20.04

    steps:
    - name: Say hello world
      run: echo "Welcome to the Github Actions workshop!"

  unit-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run unit-tests
      run: |
        make tests_run > test_output.txt 2>&1

    - name: Run coverage
      run: |
        make coverage > coverage_output.txt 2>&1

    - name: Upload coverage outputs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage_outputs
        path: |
          test_output.txt
          coverage_output.txt

  functional-test:
    runs-on: ubuntu-20.04
    container:
      image: epitechcontent/epitest-docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run functional tests
      run: |
        ./functional-test.sh > functional_test_output.txt 2>&1

    - name: Upload functional test outputs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: functional-tests_outputs
        path: |
          functional_test_output.txt
